### ISSUE TITLE
Not respecting check config for occurences

### ISSUE THREAD

**Issue by rybit** [sensu-extensions/sensu-extensions-occurrences#4]
disclaimer: I am not sure if this is the right repo for this. 

I have a config specified like this:

```
{
  "subscribers": [
    "core"
  ],
  "enable_deprecated_filtering": false,
  "standalone": true,
  "handlers": [
    "opsgenie"
  ],
  "occurrences": 5,
  "interval": 60,
  "command": "/opt/sensu/embedded/bin/check-load.rb"
}
```

not the `occurences` and then I am getting alerts on one of the boxes where the history is like this:

```
  "history": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    "check": "keepalive"
```

My anticipation is that it would have to get to having 5 1s and then on the first 0 it would clear the alert. Is that not the case?

**Comment by jothoma1** [comment]
Hi @rybit 
having the same problem, did you find something ? 
Thanks in advance
