### ISSUE TITLE
flapping action not handled

### ISSUE THREAD

**Issue by johanek** [sensu-extensions/sensu-extensions-occurrences#5]
If I use the occurrences extension and set a value for occurrences in the check config, then events with `action: flapping` are always filtered.

An example log from a simulated check:

```
{
    "message": "event was filtered",
    "event": {
      "timestamp": 1488284790,
      "id": "de6233e5-c6b2-4972-9363-0954a25de597",
      "last_state_change": 1488284790,
      "silenced_by": null,
      "check": {
        "pager_team": "engineering",
        "origin": "<redacted>",
        "name": "johan-test-incident",
        "occurrences": 5,
        "priority": "PRI-2",
        "refresh": 86400,
        "enable_deprecated_filtering": false,
        "high_flap_threshold": 30,
        "output": "The check failed but this is only a test",
        "low_flap_threshold": 10,
        "source": "<redacted>",
        "history": [
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "1",
          "0",
          "3",
          "0",
          "3",
          "0",
          "2"
        ],
        "total_state_change": 39,
        "issued": 1488284790,
        "handler": "pagerduty",
        "status": 2,
        "description": "This is a test incident for demoing pagerduty",
        "executed": 1488284790,
        "type": "standard"
      },
      "occurrences": 1,
      "client": {
        "subscriptions": null,
        "keepalives": false,
        "version": "0.28.0",
        "timestamp": 1488284052,
        "name": "<redacted>",
        "address": "unknown"
      },
      "action": "flapping",
      "silenced": false,
      "occurrences_watermark": 1,
      "last_ok": 1488284051
    },
    "filter": "occurrences",
    "level": "info",
    "timestamp": "2017-02-28T12:26:30.646492+0000",
    "handler": {
      "filters": [
        "occurrences"
      ],
      "severities": [
        "ok",
        "warning",
        "critical"
      ],
      "name": "pagerduty",
      "command": "handler-pagerduty.rb",
      "type": "pipe",
      "mutator": "xmlapi",
      "handle_flapping": true
    }
```

What I'd like to achieve is that a check must be failing for X occurrences before triggering a handler, but if it's flapping it should trigger the handler immediately.

**Comment by johanek** [comment]
Some related things: https://github.com/sensu/sensu/issues/849 and https://github.com/sensu/sensu/issues/1565

It looks straightforward to match for `action: flapping` within this extension but there doesn't seem to be any flapping history to identify when to refresh notifications or reliably send resolutions

**Comment by portertech** [comment]
Important to remember that the event occurrence count will be reset while the check status flaps. The current release does not exclude flapping events, however, refresh is not supported, so I have created https://github.com/sensu-extensions/sensu-extensions-occurrences/pull/6

**Comment by johanek** [comment]
Right, I understand what you're saying here: the flapping action won't be handled until the `occurrences` threshold is met. This requires the check to have the same status for X occurrences, not merely flapping for X occurrences.

This is OK, at least it it will catch checks that would otherwise be generating noise. But potentially you could have a device flapping, never reaching that threshold. It would be nice if the flapping occurrences threshold with was independent from the check status occurrences threshold.
